--Removing Duplicates
WITH INVOICE_NEW_CLEAN  AS(
		  SELECT * 
		  FROM [Invoice_new_data].[dbo].[Sheet1$] 
		  

		  EXCEPT


		  SELECT VENDOR,COMPANY_NAME,ACCOUNT_NUMBER,
			     BILL_DATE,INVOICE_NUMBER,
				 SUB_ACCOUNT,ASSET,BILL_TYPE,
				 TOTAL_CHARGED
		  FROM [Invoice_new_data].[dbo].[Sheet1$]
		  GROUP BY VENDOR,COMPANY_NAME,
		 		   ACCOUNT_NUMBER,BILL_DATE,
				   INVOICE_NUMBER,SUB_ACCOUNT,
				   ASSET,BILL_TYPE,TOTAL_CHARGED
		  HAVING COUNT(*) > 1
		 ) 

--records repeted from previous month
, TEMPTABLE AS (
			SELECT *, rank + 1 AS prerank
			FROM (
					SELECT [VENDOR]
					  ,[COMPANY_NAME]
					  ,[ACCOUNT_NUMBER]
					  ,[BILL_DATE]
					  ,[INVOICE_NUMBER]
					  ,[SUB_ACCOUNT]
					  ,[ASSET]
					  ,[BILL_TYPE]
					  ,[TOTAL_CHARGED]
					  ,DENSE_RANK() OVER (PARTITION BY VENDOR,COMPANY_NAME,account_number,ASSET,BILL_TYPE ORDER BY BILL_DATE) AS rank
					 FROM INVOICE_NEW_CLEAN)AS T
						)


SELECT *,
		CASE WHEN DIFF_AMOUNT = 0 THEN 'Bill With Previous Record'
		WHEN DIFF_AMOUNT > 0 OR DIFF_AMOUNT < 0 THEN 'Bill With Different Previous Record'
		END as BILL_STATUS,
		CONCAT(MONTH(BILL_DATE),'/1/',YEAR(BILL_DATE)) AS DATE
FROM (
		--Self Join to extract Previous Bills Records
		SELECT L.VENDOR 
			  ,L.COMPANY_NAME
			  ,L.ACCOUNT_NUMBER
			  ,L.BILL_DATE 
			  ,L.INVOICE_NUMBER
			  ,L.SUB_ACCOUNT
			  ,L.ASSET
			  ,L.BILL_TYPE
			  ,L.TOTAL_CHARGED
			  ,J.BILL_DATE AS PREVIOUS_BILL_DATE
			  ,J.ACCOUNT_NUMBER AS PREVIOUS_ACCOUNT_NUMBER
			  ,J.ASSET AS PREVIOUS_ASSET
			  ,J.BILL_TYPE AS PREVIOUS_BILL_TYPE
			  ,J.TOTAL_CHARGED AS PREVIOUS_BILL_AMOUNT
			  ,L.TOTAL_CHARGED - J.TOTAL_CHARGED AS DIFF_AMOUNT
			  ,(L.TOTAL_CHARGED - J.TOTAL_CHARGED)/J.TOTAL_CHARGED AS DIFF_PERCENTAGE

		from TEMPTABLE AS L
		left JOIN TEMPTABLE AS J ON
			L.RANK = J.prerank AND 
			L.ACCOUNT_NUMBER = J.ACCOUNT_NUMBER AND
			L.BILL_TYPE = J.BILL_TYPE AND 
			L.ASSET = J. ASSET
		--ORDER BY 4 DESC
) AS P

  
